# Generated by Django 4.2.5 on 2023-09-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackendDjango', '0002_multa_articulodeportivo_prestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackendDjango.articulodeportivo', unique=True),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='univalluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackendDjango.univallunos', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='univallunos',
            unique_together={('numeroDocumento', 'tipoDocumento')},
        ),
    ]
